# cando_creation package - re-exports everything for backward compatibility
from .models import *
from .prompts import *
from .generators import *
from .assembler import assemble_lesson

# Re-export everything that was in canDo_creation_new.py
__all__ = [
    # Models (from models package)
    "ImageSpec",
    "JPText",
    "LLMGenSpec",
    "CanDoMeta",
    "GraphBindings",
    "LessonMeta",
    "LookupSpec",
    "TextLayerPrefs",
    "UIPrefs",
    "DomainPlan",
    "PlanEvaluation",
    "PlanGrammarFunction",
    "PlanLexBucket",
    "PlanRole",
    "PlanScenario",
    "ComprehensionQA",
    "DialogueCard",
    "DialogueTurn",
    "GrammarPatternItem",
    "GrammarPatternsCard",
    "ObjectiveCard",
    "PatternExample",
    "PatternForm",
    "ReadingCard",
    "ReadingSection",
    "WordItem",
    "WordsCard",
    "AIComprehensionStage",
    "AIComprehensionTutorCard",
    "ComprehensionExerciseItem",
    "ComprehensionExercisesCard",
    "AIProductionEvaluationStage",
    "AIProductionEvaluatorCard",
    "ProductionExerciseItem",
    "ProductionExercisesCard",
    "AIScenarioManagerCard",
    "AIScenarioStage",
    "InteractionActivitiesCard",
    "InteractionActivityItem",
    "InteractiveDialogueCard",
    "CultureCard",
    "DrillItem",
    "DrillsCard",
    "ExerciseItem",
    "ExercisesCard",
    "FillBlankExercise",
    "FormulaicExpressionItem",
    "FormulaicExpressionsCard",
    "GuidedDialogueCard",
    "GuidedStage",
    "MatchExercise",
    "MatchPair",
    "OrderExercise",
    "PronunciationDrill",
    "PronunciationTarget",
    "SubstitutionDrill",
    "SubstitutionSeed",
    "CardsContainer",
    "Lesson",
    "LessonRoot",
    # Prompts
    "STRICT_SYSTEM",
    "build_planner_prompt",
    "build_culture_prompt",
    "build_dialogue_prompt",
    "build_drills_prompt",
    "build_exercises_prompt",
    "build_formulaic_expressions_prompt",
    "build_grammar_prompt",
    "build_grammar_prompt_from_dialogue",
    "build_guided_dialogue_prompt",
    "build_objective_prompt",
    "build_reading_prompt",
    "build_words_prompt",
    "build_words_prompt_from_dialogue",
    "build_ai_comprehension_tutor_prompt",
    "build_comprehension_exercises_prompt",
    "build_ai_production_evaluator_prompt",
    "build_production_exercises_prompt",
    "build_ai_scenario_manager_prompt",
    "build_interaction_activities_prompt",
    "build_interactive_dialogue_prompt",
    # Generators
    "LLMFn",
    "_literal_choices",
    "extract_first_json_block",
    "model_schema",
    "validate_or_repair",
    "gen_ai_comprehension_tutor_card",
    "gen_ai_production_evaluator_card",
    "gen_ai_scenario_manager_card",
    "gen_comprehension_exercises_card",
    "gen_culture_card",
    "gen_dialogue_card",
    "gen_domain_plan",
    "gen_drills_card",
    "gen_exercises_card",
    "gen_formulaic_expressions_card",
    "gen_grammar_card",
    "gen_grammar_card_from_extracted",
    "gen_guided_dialogue_card",
    "gen_interaction_activities_card",
    "gen_interactive_dialogue_card",
    "gen_objective_card",
    "gen_production_exercises_card",
    "gen_reading_card",
    "gen_words_card",
    "gen_words_card_from_extracted",
    "gen_comprehension_stage",
    "gen_content_stage",
    "gen_interaction_stage",
    "gen_production_stage",
    # Assembler
    "assemble_lesson",
]
